language: node_js
  - 10

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm i -g codecov
  - npm i

script:
  - npm run build:prod
  - npm run coverage
  - codecov
